services:
  redis:
    image: redis:7.4-alpine
    restart: always
    container_name: supermarket-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  db:
    image: timescale/timescaledb-ha:pg17
    restart: always
    container_name: supermarket-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-supermarket}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/home/postgres/pgdata/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: always
    container_name: supermarket-worker
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-supermarket}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BATCH_SIZE: ${BATCH_SIZE:-100}
      BATCH_TIME_LIMIT: ${BATCH_TIME_LIMIT:-10}
    ports:
      - "${WORKER_PORT:-6380}:6380"
    depends_on:
      - redis
      - db
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    container_name: supermarket-backend
    environment:
      IS_PROD: 'False'
      FRONTEND_URL: ${FRONTEND_URL:-localhost:3000}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-supermarket}
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:$$BACKEND_PORT | grep -q 200"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 15s
      
volumes:
  postgres_data:
  redis_data: