[project]
name = "worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.16"
dependencies = [
    "python-dotenv>=1.1.0",
    "redis>=5.0.8",
    "rq>=2.3.2",
]
